---

image: "nginx"
team: "b-team"
namespace: "kahoy-examples"

environment: 
   key1: val1
   key2: val2
   key3: val3

scalability:
  replicas: 1
  maxReplicas: 1

httpService:
  internalPort: 80

resources:
  memoryMiB: 15
  cpuMilli: 15

healthCheck:
  livePath: /
  readyPath: /
